export const data = [
    { name: "Alice", message: "Hello, how are you doing today?" },
    { name: "Bob", message: "This is a sample message for testing." },
    { name: "Charlie", message: "Happy to be part of the team!" },
    { name: "David", message: "Looking forward to the meeting." },
    { name: "Eve", message: "The project deadline is approaching fast." },
    { name: "Frank", message: "Please review the attached documents." },
    { name: "Grace", message: "Let’s catch up over coffee sometime." },
    { name: "Heidi", message: "Don't forget to submit your reports." },
    { name: "Ivan", message: "Can we reschedule our appointment?" },
    { name: "Judy", message: "Congratulations on your promotion!" },
    { name: "Mallory", message: "The event starts at 6 PM sharp." },
    { name: "Niaj", message: "Here are the latest project updates." },
    { name: "Olivia", message: "Thank you for your quick response." },
    { name: "Peggy", message: "Is there any progress on the task?" },
    { name: "Quentin", message: "Please send me the final report." },
    { name: "Rupert", message: "I appreciate your hard work and effort." },
    { name: "Sybil", message: "Let's discuss the budget tomorrow." },
    { name: "Trent", message: "Team meeting at 10 AM in the conference room." },
    { name: "Uma", message: "Looking forward to your presentation." },
    { name: "Victor", message: "Let's brainstorm ideas for the new project." },
    { name: "Wendy", message: "Can you send me the updated schedule?" },
    { name: "Xander", message: "I'm excited about the new opportunity." },
    { name: "Yvonne", message: "We need to finalize the details by Friday." },
    { name: "Zara", message: "Please prepare the agenda for the meeting." },
    { name: "Aaron", message: "Let me know if you need any help." },
    { name: "Bella", message: "I’ll be out of the office next week." },
    { name: "Carter", message: "Please confirm your attendance." },
    { name: "Diana", message: "Don't forget to check your email." },
    { name: "Ethan", message: "Please provide your feedback." },
    { name: "Fiona", message: "The deadline has been extended." },
    { name: "George", message: "Thank you for the update." },
    { name: "Hannah", message: "I'll get back to you soon." },
    { name: "Isaac", message: "Looking forward to our collaboration." },
    { name: "Jessica", message: "We need to improve our strategy." },
    { name: "Kevin", message: "Please find the attachment below." },
    { name: "Laura", message: "Our meeting has been rescheduled." },
    { name: "Michael", message: "Let's focus on the key issues." },
    { name: "Nina", message: "The report is due by end of day." },
    { name: "Oscar", message: "I have some ideas to share." },
    { name: "Paula", message: "Can we discuss this over a call?" },
    { name: "Quincy", message: "Your input is valuable to us." },
    { name: "Rachel", message: "I'll send you the details shortly." },
    { name: "Samuel", message: "Thanks for the quick turnaround." },
    { name: "Tina", message: "Our team did a fantastic job!" },
    { name: "Ulysses", message: "Looking forward to the weekend." },
    { name: "Vanessa", message: "We need to finalize our plan." },
    { name: "William", message: "Please join the conference call." },
    { name: "Xena", message: "The proposal looks good to me." },
    { name: "Yusuf", message: "Can you provide more details?" },
    { name: "Zoey", message: "Great job on the presentation!" },
    { name: "Abigail", message: "Please review the new guidelines." },
    { name: "Blake", message: "Our client meeting is on Monday." },
    { name: "Caitlyn", message: "Let me know your availability." },
    { name: "Derek", message: "Can you send the updated version?" },
    { name: "Elena", message: "Happy to assist you with this task." },
    { name: "Felix", message: "I'll follow up with you later." },
    { name: "Gina", message: "Our project is moving forward." },
    { name: "Harry", message: "Thank you for your assistance." },
    { name: "Irene", message: "I'll be in touch soon." },
    { name: "Jack", message: "Can we meet to discuss this?" },
    { name: "Karen", message: "Let's review the contract." },
    { name: "Liam", message: "The launch is next week." },
    { name: "Mia", message: "Our team is ready to start." },
    { name: "Noah", message: "Can you send me the details?" },
    { name: "Olga", message: "Please share the meeting notes." },
    { name: "Peter", message: "We need to finalize the design." },
    { name: "Quinn", message: "I'll be attending the seminar." },
    { name: "Ruby", message: "Let's catch up later." },
    { name: "Steve", message: "I have an important update." },
    { name: "Tara", message: "Can you join the team call?" },
    { name: "Umar", message: "I'll send the report by tomorrow." },
    { name: "Violet", message: "Our progress is impressive." },
    { name: "Wesley", message: "We need more information." },
    { name: "Xavier", message: "Thank you for your feedback." },
    { name: "Yara", message: "Please confirm the dates." },
    { name: "Zeke", message: "I'll keep you updated." },
    { name: "Amelia", message: "Can we schedule a meeting?" },
    { name: "Brett", message: "I appreciate your support." },
    { name: "Clara", message: "Let's finalize the agenda." },
    { name: "Dylan", message: "I'm working on the proposal." },
    { name: "Eva", message: "Our team is doing great." },
    { name: "Finn", message: "I'll send you the documents." },
    { name: "Grace", message: "The budget has been approved." },
    { name: "Henry", message: "Please update the status." },
    { name: "Isla", message: "Thank you for the invitation." },
    { name: "James", message: "I'll review it today." },
    { name: "Kara", message: "We need to discuss the plan." },
    { name: "Leo", message: "I'll see you at the meeting." },
    { name: "Maya", message: "Our project is on track." },
    { name: "Nathan", message: "Let's catch up next week." },
    { name: "Olive", message: "I'm looking into it." },
    { name: "Paul", message: "I'll send an update soon." },
    { name: "Quin", message: "Thank you for your effort." },
    { name: "Rose", message: "Let's coordinate on this." },
    { name: "Sean", message: "I have some questions." },
    { name: "Tina", message: "Please let me know." },
    { name: "Usha", message: "I'll get back to you." },
    { name: "Victor", message: "Our team is amazing." },
    { name: "Willa", message: "I'm on it." },
    { name: "Xena", message: "Lorem ipsum dolor" },
  ];